runtime: nodejs14
service: default
env_variables:
  PORT: 8080
handlers:
  - url: /.*
    script: auto
    secure: always
    headers:
      Content-Security-Policy: same-origin
  - url: /static
    static_dir: build/static
  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$
  - url: /media/(.*\.(jpg|png|gif))$
    static_files: media/\1
    upload: media/.*\.(jpg|png|gif)$
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always
